name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Print environment information
        run: |
          echo "Java Version:"
          java -version
          echo "Gradle Version:"
          ./gradlew --version
          
      - name: Clear Gradle Cache
        run: ./gradlew clean build --refresh-dependencies
      - name: Dependency Check
        run: ./gradlew dependencies
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Access SUPABASE_URL
        env:
          APOD_API_KEY: ${{ secrets.SUPABASE_URL}}
        run: echo APOD_API_KEY=\"$SUPABASE_URL\" > ./local.properties
      - name: Access SUPABASE_KEY
        env:
          APOD_API_KEY: ${{ secrets.SUPABASE_KEY}}
        run: echo APOD_API_KEY=\"$SUPABASE_KEY\" > ./local.properties
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build the app
        run: ./gradlew assembleDebug
