name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Print environment information
        run: |
          echo "Java Version:"
          java -version
          echo "Gradle Version:"
          ./gradlew --version
      - name: Access SUPABASE_URL
        env:
          APOD_API_KEY: ${{ secrets.SUPABASE_URL}}
        run: echo APOD_API_KEY=\"$SUPABASE_URL\" > ./local.properties
      - name: Access SUPABASE_KEY
        env:
          APOD_API_KEY: ${{ secrets.SUPABASE_KEY}}
        run: echo APOD_API_KEY=\"$SUPABASE_KEY\" > ./local.properties
      - name: Install Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4

      - name: Build with specific Gradle version
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle build 
