name: Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Create local.properties file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> local.properties
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> local.properties
          cat local.properties  # Display the content for verification

      - name: Build and test the library
        run: ./gradlew build  # Modify this command based on your library's build process
